# Generated by Django 3.0.6 on 2020-11-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_remove_topic_min_percent_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticgraph',
            name='image',
        ),
    ]
