# Generated by Django 3.0.6 on 2020-11-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20200509_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
